import type { AnswerValue, CareerProfile, CareerScores, CareerType, ExperienceMission, Question, SeoulCareerActivity } from './types';

export const careerTypes: CareerType[] = ['investigative', 'artistic', 'social'];

export const initialScores: CareerScores = {
  investigative: 0,
  artistic: 0,
  social: 0,
};

export const answerOptions: { label: string; value: AnswerValue }[] = [
  { label: '그렇지 않다', value: 0 },
  { label: '보통이다', value: 1 },
  { label: '그렇다', value: 2 },
];

export const maxTypeScore = 34;

export const profiles: Record<CareerType, CareerProfile> = {
  investigative: {
    type: 'investigative',
    title: '탐구형',
    label: '미래를 여는 꼬마 과학자',
    nickname: '지적 탐험가',
    icon: '🔬',
    color: '#2F80ED',
    softColor: '#EAF3FF',
    imageCaption: '관찰, 실험, 분석을 즐기는 탐구 이미지',
    description:
      '현상의 원인을 논리적으로 분석하고 복잡한 문제를 하나씩 풀어갈 때 깊은 흥미를 느끼는 유형입니다. 주변 사물을 보며 "왜 그럴까?"라는 질문을 자주 던지는 관찰력이 강해요.',
    guide:
      '정답을 외우는 활동보다 스스로 가설을 세우고 실험과 데이터로 확인하는 환경에서 강점이 잘 드러납니다.',
    personality:
      '차분하게 관찰하고 근거를 모아 판단하는 편입니다. 복잡한 문제를 만나도 쉽게 포기하지 않고, 자료를 비교하며 가장 타당한 답을 찾으려는 힘이 큽니다.',
    recommendedJobs: ['AI 연구원', '데이터 분석가', '의사 또는 생명과학자', '로봇공학자', '소프트웨어 개발자'],
    missionStory:
      '별빛 실험실의 작은 문이 열렸어요. 호기심 나침반을 들고 원리의 숲을 지나 미래 기술의 성으로 향해 보세요.',
    missionTasks: ['궁금한 현상 1가지를 관찰 일지에 적기', '자료를 찾아 원인 가설 2개 세우기', '작은 실험이나 코딩 결과물을 완성하기'],
    roadmapTitle: '미래를 여는 꼬마 과학자 로드맵',
    roadmapSummary: '과학 원리 체험부터 미래 기술, 코딩 캠프까지 이어지는 탐구형 성장 경로입니다.',
    roadmap: [
      {
        step: '1단계',
        title: '기초 과학 원리 온몸으로 체험하기',
        place: '서울시립과학관(노원구)',
        quest: '일상 속 과학 원리 전시를 관람하고 가장 신기했던 원리 1가지를 퀘스트 일지에 기록하기',
      },
      {
        step: '2단계',
        title: '최신 미래 기술 트렌드 마스터하기',
        place: '서울로봇인공지능과학관, 서울시교육청 융합과학교육원',
        quest: 'AI 로봇 도슨트 투어와 자율주행, 인공지능 작동 원리 교육 참여하기',
      },
      {
        step: '3단계',
        title: '나만의 상상을 현실로 만드는 코딩 캠프',
        place: '이노베이션 아카데미 또는 서울시내 소프트웨어 체험센터',
        quest: '엔트리나 스크래치로 나만의 미니 프로그램을 완성하고 결과물 인증하기',
      },
    ],
  },
  artistic: {
    type: 'artistic',
    title: '예술형',
    label: '트렌디한 디지털 크리에이터',
    nickname: '아이디어 크리에이터',
    icon: '🎨',
    color: '#E0568A',
    softColor: '#FFF0F5',
    imageCaption: '창작, 표현, 감각을 즐기는 예술 이미지',
    description:
      '틀에 박힌 규칙보다 자유로운 환경에서 나만의 생각과 감정을 표현할 때 행복한 유형입니다. 독창적인 감각과 아름다움을 알아보는 눈을 지녔어요.',
    guide:
      '반복적인 일보다 새로운 변화가 있는 환경이 어울리며, 시각 예술, 음악, 미디어 콘텐츠로 세상과 소통할 때 빛을 발합니다.',
    personality:
      '감정과 상상을 섬세하게 붙잡아 자기만의 방식으로 표현하는 편입니다. 정해진 답보다 새로운 해석을 좋아하고, 분위기와 아름다움을 빠르게 알아차립니다.',
    recommendedJobs: ['콘텐츠 크리에이터', '웹툰 작가', '영상 편집자', 'UX/UI 디자이너', '공연 또는 전시 기획자'],
    missionStory:
      '무지개 작업실에 반짝이는 붓이 놓였어요. 상상의 정원을 걸으며 나만의 작품 씨앗을 키워 보세요.',
    missionTasks: ['하루 동안 떠오른 아이디어 3개 스케치하기', '사진, 글, 영상 중 하나로 짧은 작품 만들기', '작품에 제목을 붙이고 친구에게 소개하기'],
    roadmapTitle: '트렌디한 디지털 크리에이터 로드맵',
    roadmapSummary: '시각 예술 감상에서 미디어 제작, 작품 발표까지 이어지는 예술형 성장 경로입니다.',
    roadmap: [
      {
        step: '1단계',
        title: '현대 미술과 시각 예술 감각 깨우기',
        place: '서울시립 미술아카이브(종로구) 또는 DDP 디자인랩(중구)',
        quest: '가장 영감을 준 디자인 작품을 사진으로 남기고 한 줄 평 작성하기',
      },
      {
        step: '2단계',
        title: '내 손으로 만드는 미디어 콘텐츠 기획',
        place: "서울시립청소년미디어센터 '스스로넷'(용산구)",
        quest: '웹툰, 사진, 영상 편집 중 하나의 원데이 클래스를 수강하기',
      },
      {
        step: '3단계',
        title: '세상에 내 작품을 선보이는 크리에이터 데뷔',
        place: '시립 청소년센터 미디어 동아리 또는 대한민국청소년미디어대전',
        quest: '직접 만든 단편 영상이나 캐릭터 디자인을 축제 또는 공모전에 출품하기',
      },
    ],
  },
  social: {
    type: 'social',
    title: '사회형',
    label: '마음을 치유하는 청소년 멘토, 리더',
    nickname: '다정한 리더',
    icon: '🤝',
    color: '#27AE60',
    softColor: '#EAF8EF',
    imageCaption: '공감, 소통, 협력을 즐기는 사회형 이미지',
    description:
      '주변 사람들의 마음에 공감하고 누군가를 도와주거나 가르쳐 줄 때 큰 보람을 느끼는 유형입니다. 친구들의 고민을 잘 들어주고 소통을 이끄는 따뜻한 에너지가 있어요.',
    guide:
      '혼자 일하는 환경보다 다양한 사람과 만나 긍정적인 영향을 전하고 공동체의 문제를 함께 해결하는 환경이 잘 맞습니다.',
    personality:
      '사람의 표정과 마음 변화를 잘 살피고 관계 속에서 에너지를 얻는 편입니다. 누군가를 돕거나 함께 문제를 해결할 때 책임감과 따뜻함이 자연스럽게 드러납니다.',
    recommendedJobs: ['상담사', '교사', '간호사', '사회복지사', '청소년 지도사'],
    missionStory:
      '햇살 마을에 도움이 필요한 친구들이 기다리고 있어요. 다정한 마음 등불을 들고 함께 자라는 길을 밝혀 보세요.',
    missionTasks: ['친구의 고민을 끝까지 듣고 공감 문장 적기', '작은 도움이나 봉사 활동 1가지 실천하기', '함께한 사람에게 고마운 점을 말해주기'],
    roadmapTitle: '마음을 치유하는 청소년 멘토, 리더 로드맵',
    roadmapSummary: '공감 리더십, 또래 상담, 지역사회 활동으로 이어지는 사회형 성장 경로입니다.',
    roadmap: [
      {
        step: '1단계',
        title: '타인과 소통하고 공감하는 리더십 배우기',
        place: '서울시립청소년활동진흥센터(동작구)',
        quest: '청소년 인성 교육 프로그램과 공동체 협동 게임에 참여하기',
      },
      {
        step: '2단계',
        title: '우리 동네 친구들의 마음을 돌보는 또래 상담가',
        place: '자치구별 시립 청소년센터 또는 청소년상담복지센터',
        quest: '또래 상담가 기획 교실을 수료하고 배운 대화법을 정리하기',
      },
      {
        step: '3단계',
        title: '따뜻한 사회를 만드는 지역사회 체인지메이커',
        place: '청소년 자원봉사 포털 두볼(Dovol), 서울 지역 봉사처',
        quest: '환경 캠페인, 플로깅, 돌봄 봉사 중 하나를 완료하고 활동 기록 남기기',
      },
    ],
  },
};




export const experienceMissions: ExperienceMission[] = [
  {
    id: 'exp-science-visit',
    type: 'investigative',
    title: '과학관 방문 인증',
    activity: '서울시립과학관 방문 후 가장 인상 깊었던 전시 기록하기',
    description: '과학 전시를 직접 보고 관찰한 내용을 바탕으로 탐구형 경험치를 얻습니다.',
    proofType: 'gps',
    xp: 14,
    lat: 37.6428,
    lng: 127.0773,
  },
  {
    id: 'exp-coding-proof',
    type: 'investigative',
    title: '코딩 체험 결과 인증',
    activity: '스크래치, 엔트리, 파이썬 중 하나로 만든 결과물 기록하기',
    description: '작은 프로그램을 완성하고 파일명이나 링크를 남기면 탐구형 점수가 올라갑니다.',
    proofType: 'photo',
    xp: 16,
  },
  {
    id: 'exp-artifact-photo',
    type: 'artistic',
    title: '창작물 사진 인증',
    activity: '그림, 영상 썸네일, 디자인 시안 등 내가 만든 창작물 기록하기',
    description: '창작 결과물을 남기고 표현 과정을 돌아보며 예술형 경험치를 얻습니다.',
    proofType: 'photo',
    xp: 15,
  },
  {
    id: 'exp-design-qr',
    type: 'artistic',
    title: '디자인 전시 QR 인증',
    activity: 'DDP 또는 전시 공간을 둘러본 뒤 현장 QR 코드를 입력하기',
    description: '전시와 디자인 공간을 직접 경험한 기록을 통해 예술형 점수를 갱신합니다.',
    proofType: 'qr',
    xp: 13,
    qrCode: 'ART-DDP-2026',
  },
  {
    id: 'exp-interview-reflection',
    type: 'social',
    title: '직업인 인터뷰 소감 인증',
    activity: '교사, 상담사, 청소년지도사 등 사람을 돕는 직업 인터뷰를 보고 소감 쓰기',
    description: '직업인의 이야기를 듣고 나의 관심과 맞는 부분을 정리하면 사회형 경험치를 얻습니다.',
    proofType: 'reflection',
    xp: 12,
  },
  {
    id: 'exp-volunteer-gps',
    type: 'social',
    title: '청소년 활동센터 방문 인증',
    activity: '서울시립청소년활동진흥센터 또는 지역 청소년센터 활동 참여하기',
    description: '사람들과 함께하는 활동을 실제 위치 기반으로 인증해 사회형 점수를 갱신합니다.',
    proofType: 'gps',
    xp: 15,
    lat: 37.4957,
    lng: 126.9171,
  },
];

export const seoulCareerActivities: SeoulCareerActivity[] = [
  {
    id: 'science-museum-nowon',
    district: '노원구',
    title: '과학 전시 탐구 활동',
    place: '서울시립과학관',
    address: '서울 노원구 한글비석로 160',
    info: '상설 과학 전시를 관람하며 자연, 기술, 실험 원리를 탐구하는 활동입니다. 탐구형 학생에게 잘 맞습니다.',
    lat: 37.6428,
    lng: 127.0773,
    sourceUrl: 'https://science.seoul.go.kr/',
    types: ['investigative'],
    minAge: 9,
    maxAge: 15,
    keywords: ['과학', '전시', '실험', '탐구'],
  },
  {
    id: 'robot-ai-dobong',
    district: '도봉구',
    title: '로봇·인공지능 진로 체험',
    place: '서울로봇인공지능과학관',
    address: '서울 도봉구 마들로13길 56',
    info: '로봇, 인공지능, 미래 기술 전시와 교육 프로그램을 통해 기술 분야 진로를 살펴보는 활동입니다.',
    lat: 37.6552,
    lng: 127.0502,
    sourceUrl: 'https://seoulrobotai.org/',
    types: ['investigative'],
    minAge: 10,
    maxAge: 16,
    keywords: ['로봇', '인공지능', 'AI', '기술'],
  },
  {
    id: 'media-yongsan',
    district: '용산구',
    title: '청소년 미디어 제작 체험',
    place: '서울시립청소년미디어센터 스스로넷',
    address: '서울 용산구 한강대로 255',
    info: '영상, 사진, 라디오, 미디어 콘텐츠 제작 과정을 경험하며 예술형·미디어 분야 진로를 탐색합니다.',
    lat: 37.5425,
    lng: 126.973,
    sourceUrl: 'https://www.ssro.net/',
    types: ['artistic'],
    minAge: 11,
    maxAge: 18,
    keywords: ['미디어', '영상', '사진', '콘텐츠'],
  },
  {
    id: 'design-ddp-jung',
    district: '중구',
    title: '디자인·전시 감상 활동',
    place: 'DDP 디자인랩',
    address: '서울 중구 을지로 281',
    info: '디자인 전시와 창작 공간을 둘러보며 시각 디자인, 전시 기획, 창작 직무를 탐색하는 활동입니다.',
    lat: 37.5665,
    lng: 127.0092,
    sourceUrl: 'https://www.ddp.or.kr/',
    types: ['artistic'],
    minAge: 10,
    maxAge: 18,
    keywords: ['디자인', '전시', '창작', '기획'],
  },
  {
    id: 'youth-volunteer-dongjak',
    district: '동작구',
    title: '청소년 활동·리더십 프로그램',
    place: '서울시립청소년활동진흥센터',
    address: '서울 동작구 여의대방로20길 33',
    info: '청소년 활동, 봉사, 리더십 정보를 확인하고 사회형 진로와 연결되는 활동을 찾아볼 수 있습니다.',
    lat: 37.4957,
    lng: 126.9171,
    sourceUrl: 'https://www.sy0404.or.kr/',
    types: ['social'],
    minAge: 10,
    maxAge: 18,
    keywords: ['청소년', '봉사', '리더십', '소통'],
  },
  {
    id: 'career-seoul-center',
    district: '영등포구',
    title: '진로직업체험지원센터 프로그램',
    place: '자치구 진로직업체험지원센터 연계 활동',
    address: '서울 영등포구 일대',
    info: '서울 자치구별 진로직업체험지원센터에서 학교·지역 연계 진로 체험과 직업인 만남 프로그램을 확인할 수 있습니다.',
    lat: 37.5264,
    lng: 126.8962,
    sourceUrl: 'https://www.career.go.kr/',
    types: ['investigative', 'artistic', 'social'],
    minAge: 9,
    maxAge: 18,
    keywords: ['진로', '직업', '체험', '상담'],
  },
];

export const questions: Question[] = [
  { id: 'i1', type: 'investigative', text: '과학 책을 읽거나 새로운 기술 방법(AI, 로봇 등)을 알아내는 것이 재밌다.' },
  { id: 'i2', type: 'investigative', text: '수수께끼나 수학 문제처럼 답이 복잡한 문제를 끝까지 풀어내는 걸 좋아한다.' },
  { id: 'i3', type: 'investigative', text: '주변 사물이나 현상을 보면 "이건 어떻게 움직이는 걸까?" 하고 혼자 생각해보곤 한다.' },
  { id: 'i4', type: 'investigative', text: '컴퓨터 프로그램이나 스마트폰 앱이 작동하는 내부 구조에 호기심이 생긴다.' },
  { id: 'i5', type: 'investigative', text: '무언가를 결정할 때 기분에 따라 행동하기보다 정확한 사실과 숫자로 정리한 것을 바탕으로 하는 편이다.' },
  { id: 'i6', type: 'investigative', text: '돋보기, 현미경, 실험 도구 등을 사용해 물건을 자세히 관찰하고 생각하는 활동이 즐겁다.' },
  { id: 'i7', type: 'investigative', text: '한 가지 주제에 꽂히면 책이나 인터넷으로 찾아서 깊이 있게 끝까지 알아보는 성격이다.' },
  { id: 'i8', type: 'investigative', text: '친구들과 수다를 떠는 것보다 혼자 조용히 새로운 것을 공부하는 시간이 좋다.' },
  { id: 'i9', type: 'investigative', text: '새로운 물건이나 전자기기(핸드폰)가 나오면 하는 일과 자세한 정보를 살펴본다.' },
  { id: 'i10', type: 'investigative', text: '"그냥 그래"라는 말보다 "왜냐하면"으로 시작하는 논리적인 설명이 좋다.' },
  { id: 'i11', type: 'investigative', text: '역사 이야기나 자연에서 일어나는 일을 표나 그래프로 정리하면 이해하기 쉽다.' },
  { id: 'i12', type: 'investigative', text: '문제가 생기면 놀라기보다 왜 그런지 차분히 찾는다.' },
  { id: 'i13', type: 'investigative', text: '말이 안 되는 부분이나 남들의 말에서 앞뒤가 다른 점을 잘 발견하는 편이다.' },
  { id: 'i14', type: 'investigative', text: '외워야 하는 과목보다 공식 하나로 여러 문제를 푸는 과목이 더 잘 맞는다.' },
  { id: 'i15', type: 'investigative', text: '체스, 바둑 또는 작전을 잘 세워야 하는 보드게임을 즐긴다.' },
  { id: 'i16', type: 'investigative', text: '몸의 구조, 의학 지식, 또는 범죄를 조사하는 방법 같은 일에 호기심이 생긴다.' },
  { id: 'i17', type: 'investigative', text: '세상의 모든 일에는 반드시 이유와 규칙이 있다고 믿는다.' },
  { id: 'a1', type: 'artistic', text: '그림, 음악, 글쓰기, 영상 만들기처럼 내 생각으로 새로운 것을 만들 때 행복하다.' },
  { id: 'a2', type: 'artistic', text: '정해진 규칙대로 움직이는 것보다 내가 하고 싶은 대로 자유롭게 하는 게 편하다.' },
  { id: 'a3', type: 'artistic', text: '내 방이나 옷을 남들과 다르게 꾸미는 걸 좋아한다.' },
  { id: 'a4', type: 'artistic', text: '예쁜 풍경이나 멋진 물건, 예술 작품을 보면 쉽게 감동받는다.' },
  { id: 'a5', type: 'artistic', text: '답이 하나인 문제보다 여러 가지 생각을 할 수 있는 질문이 더 좋다.' },
  { id: 'a6', type: 'artistic', text: '일기나 낙서를 하면서 내 마음을 표현하는 걸 좋아한다.' },
  { id: 'a7', type: 'artistic', text: '매일 똑같은 생활보다 새로운 일과 모험이 많은 게 좋다.' },
  { id: 'a8', type: 'artistic', text: '영화나 소설을 보면 결말을 내 마음대로 상상해보기도 한다.' },
  { id: 'a9', type: 'artistic', text: '남들이 생각하지 못한 재미있고 새로운 생각을 잘 떠올린다.' },
  { id: 'a10', type: 'artistic', text: '교복이나 물건을 내 취향대로 꾸미는 걸 잘한다.' },
  { id: 'a11', type: 'artistic', text: '악기 연주나 노래를 할 때 내 감정을 담아서 표현하는 편이다.' },
  { id: 'a12', type: 'artistic', text: '계획을 딱 정해두기보다 그날 기분에 따라 움직이는 편이다.' },
  { id: 'a13', type: 'artistic', text: '유행하는 영상이나 밈을 내 방식대로 바꿔보고 싶다.' },
  { id: 'a14', type: 'artistic', text: '"얌전하고 착하다"보다 "개성 있고 매력 있다"는 말을 더 좋아한다.' },
  { id: 'a15', type: 'artistic', text: '글을 쓸 때 단어 느낌이나 문장 분위기를 예쁘게 만드는 데 신경 쓴다.' },
  { id: 'a16', type: 'artistic', text: '단체 규칙이나 똑같은 옷처럼 정해진 대로 해야 하는 규칙이 답답하게 느껴진다.' },
  { id: 'a17', type: 'artistic', text: '다른 사람의 평가보다 내가 즐겁고 만족하는 게 더 중요하다.' },
  { id: 's1', type: 'social', text: '친구가 속상한 일을 이야기하면 진심으로 공감해주고 위로해주고 싶다.' },
  { id: 's2', type: 'social', text: '대화할 때 내 이야기만 하지 않고 상대방 말을 끝까지 잘 듣고 반응해준다.' },
  { id: 's3', type: 'social', text: '친구들이 나를 "비밀을 잘 지켜주는 편한 고민 상담 친구"라고 생각하고 의지한다.' },
  { id: 's4', type: 'social', text: '말을 할 때 상대방이 상처받지 않도록 예쁘고 다정하게 말하려고 노력한다.' },
  { id: 's5', type: 'social', text: '내가 새롭게 알게 된 좋은 정보를 다른 사람에게 친절하게 알려줄 때 뿌듯하다.' },
  { id: 's6', type: 'social', text: '아픈 사람을 돌보거나 어린아이와 놀아주는 일이 힘들지 않고 즐겁다.' },
  { id: 's7', type: 'social', text: '나 때문에 다른 사람이 기뻐하는 모습을 보면 뿌듯하다.' },
  { id: 's8', type: 'social', text: '혼자 노는 것보다 친구들과 함께 힘을 모아 목표(게임, 모둠활동)를 이루는 게 즐겁다.' },
  { id: 's9', type: 'social', text: '처음 만난 사람과도 자연스럽게 이야기하고, 친구들 사이에 다툼이 생기면 사이를 잘 풀어준다.' },
  { id: 's10', type: 'social', text: '친구들의 생일이나 특별한 날을 기억했다가 편지나 선물을 챙겨준다.' },
  { id: 's11', type: 'social', text: '다른 사람의 좋은 점을 잘 찾고 칭찬도 잘한다.' },
  { id: 's12', type: 'social', text: '새로 온 친구가 있으면 먼저 다가가 적응할 수 있게 도와준다.' },
  { id: 's13', type: 'social', text: '외롭거나 슬퍼하는 사람이 있으면 먼저 다가가 말을 걸고 도와준다.' },
  { id: 's14', type: 'social', text: '사람들의 성격이나 왜 그런 행동을 하는지에 관심이 많다.' },
  { id: 's15', type: 'social', text: '우리 동네나 학교를 더 따뜻하고 좋은 곳으로 만드는 활동에 관심이 있다.' },
  { id: 's16', type: 'social', text: '"일을 빨리 잘한다"보다 "따뜻하고 믿음직하다"는 말을 더 좋아한다.' },
  { id: 's17', type: 'social', text: '세상은 똑똑한 사람보다 서로 도와주는 따뜻한 사람들 덕분에 더 좋아진다고 생각한다.' },
];

export const tieBreakerQuestions: Record<CareerType, Question[]> = {
  investigative: [
    {
      id: 'tie-i1',
      type: 'investigative',
      text: '새로운 문제를 만나면 바로 답을 보기보다 원인을 추리하며 해결해보고 싶다.',
    },
    {
      id: 'tie-i2',
      type: 'investigative',
      text: '내가 좋아하는 주제를 깊이 조사해서 다른 사람에게 정확하게 설명하는 일이 즐겁다.',
    },
  ],
  artistic: [
    {
      id: 'tie-a1',
      type: 'artistic',
      text: '같은 과제라도 나만의 색깔이 드러나도록 표현 방식을 바꾸고 싶다.',
    },
    {
      id: 'tie-a2',
      type: 'artistic',
      text: '생각이나 감정을 그림, 글, 음악, 영상 같은 창작물로 남길 때 가장 만족스럽다.',
    },
  ],
  social: [
    {
      id: 'tie-s1',
      type: 'social',
      text: '친구나 가족이 힘들어할 때 곁에서 이야기를 들어주고 해결 방법을 함께 찾고 싶다.',
    },
    {
      id: 'tie-s2',
      type: 'social',
      text: '여러 사람이 함께하는 활동에서 분위기를 살피고 모두가 참여하도록 돕는 편이다.',
    },
  ],
};
