import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F7FBFF',
  },
  container: {
    padding: 20,
    paddingBottom: 36,
  },
  hero: {
    minHeight: 520,
    borderRadius: 24,
    backgroundColor: '#FFF7D6',
    padding: 22,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#FFE08A',
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  brand: {
    color: '#1F2A44',
    fontSize: 24,
    fontWeight: '900',
  },
  badge: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderWidth: 1,
    borderColor: '#DDEBFF',
  },
  badgeText: {
    color: '#315078',
    fontSize: 12,
    fontWeight: '800',
  },
  heroContent: {
    flex: 1,
    justifyContent: 'center',
    paddingVertical: 36,
  },
  heroImage: {
    width: 118,
    height: 118,
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 22,
    borderWidth: 1,
    borderColor: '#FFE08A',
  },
  heroIcon: {
    fontSize: 58,
  },
  eyebrow: {
    color: '#2F80ED',
    fontSize: 15,
    fontWeight: '900',
    marginBottom: 10,
  },
  title: {
    color: '#1F2A44',
    fontSize: 34,
    lineHeight: 42,
    fontWeight: '900',
    maxWidth: 350,
  },
  subtitle: {
    color: '#42526E',
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
    marginTop: 14,
    maxWidth: 350,
  },
  homeResultCard: {
    maxWidth: 350,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    padding: 14,
    marginTop: 18,
  },
  homeResultLabel: {
    color: '#52657A',
    fontSize: 13,
    fontWeight: '900',
    marginBottom: 8,
  },
  homeResultRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  homeResultIcon: {
    fontSize: 34,
  },
  homeResultTextWrap: {
    flex: 1,
  },
  homeResultTitle: {
    fontSize: 20,
    fontWeight: '900',
  },
  homeResultSubtitle: {
    color: '#40566F',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '700',
    marginTop: 3,
  },
  primaryButton: {
    minHeight: 56,
    borderRadius: 18,
    backgroundColor: '#2F80ED',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    shadowColor: '#1D5FBF',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.16,
    shadowRadius: 14,
    elevation: 5,
    overflow: 'hidden',
  },
  pressed: {
    opacity: 0.72,
    transform: [{ scale: 0.98 }],
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '900',
    textAlign: 'center',
  },
  diaryHomeButton: {
    minHeight: 52,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#FFE08A',
    marginTop: 12,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  diaryHomeButtonLocked: {
    backgroundColor: '#E6E9EE',
    borderColor: '#CBD3DD',
  },
  diaryHomeIcon: {
    fontSize: 22,
  },
  diaryHomeTextWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  diaryHomeText: {
    color: '#1F2A44',
    fontSize: 16,
    fontWeight: '900',
  },
  diaryHomeTextLocked: {
    color: '#7A8795',
  },
  diaryHomeLockText: {
    color: '#8A96A5',
    fontSize: 12,
    fontWeight: '800',
  },

  activityMapHomeButton: {
    minHeight: 86,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#DDEBFF',
    marginTop: 18,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  activityMapHomeIcon: {
    fontSize: 30,
  },
  activityMapHomeTextWrap: {
    flex: 1,
  },
  activityMapHomeTitle: {
    color: '#1F2A44',
    fontSize: 18,
    fontWeight: '900',
    marginBottom: 5,
  },
  activityMapHomeText: {
    color: '#52657A',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '700',
  },

  postSurveyShortcutPanel: {
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#DDEBFF',
    padding: 18,
    marginTop: 18,
  },
  postSurveyShortcutTitle: {
    color: '#1F2A44',
    fontSize: 19,
    fontWeight: '900',
    marginBottom: 6,
  },
  postSurveyShortcutText: {
    color: '#52657A',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '700',
    marginBottom: 14,
  },
  postSurveyShortcutGrid: {
    flexDirection: 'row',
    gap: 9,
  },
  postSurveyShortcutButton: {
    flex: 1,
    minHeight: 92,
    borderRadius: 16,
    backgroundColor: '#F7FBFF',
    borderWidth: 1,
    borderColor: '#E3EDF8',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
  },
  postSurveyShortcutIcon: {
    fontSize: 25,
    marginBottom: 7,
  },
  postSurveyShortcutLabel: {
    color: '#1F2A44',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '900',
    textAlign: 'center',
  },
  typeGrid: {
    marginTop: 18,
    gap: 12,
  },
  typeCard: {
    minHeight: 116,
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: '#E3EDF8',
  },
  typeIcon: {
    fontSize: 34,
    marginBottom: 8,
  },
  typeTitle: {
    color: '#1F2A44',
    fontSize: 19,
    fontWeight: '900',
  },
  typeDescription: {
    color: '#52657A',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '700',
    marginTop: 4,
  },

  typeCardSelected: {
    borderWidth: 2,
  },
  typeCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  typeCardTitleWrap: {
    flex: 1,
  },
  typeToggle: {
    fontSize: 13,
    fontWeight: '900',
  },
  typeDetailBox: {
    marginTop: 14,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E3EDF8',
    padding: 14,
  },
  typeDetailTitle: {
    color: '#1F2A44',
    fontSize: 14,
    fontWeight: '900',
    marginBottom: 6,
  },
  typeDetailText: {
    color: '#40566F',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '600',
    marginBottom: 12,
  },
  surveyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  progressText: {
    color: '#52657A',
    fontSize: 14,
    fontWeight: '800',
  },
  progressTrack: {
    height: 12,
    borderRadius: 8,
    backgroundColor: '#E3EDF8',
    overflow: 'hidden',
    marginBottom: 18,
  },
  progressFill: {
    height: '100%',
    borderRadius: 8,
    backgroundColor: '#2F80ED',
  },
  questionCard: {
    minHeight: 260,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E3EDF8',
    padding: 22,
    justifyContent: 'center',
  },
  questionTypeBadge: {
    alignSelf: 'flex-start',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 7,
    marginBottom: 22,
  },
  questionTypeText: {
    fontSize: 13,
    fontWeight: '900',
  },
  questionNumber: {
    color: '#8A9AAF',
    fontSize: 18,
    fontWeight: '900',
    marginBottom: 10,
  },
  questionText: {
    color: '#1F2A44',
    fontSize: 24,
    lineHeight: 34,
    fontWeight: '900',
  },
  answerList: {
    marginTop: 16,
    gap: 10,
  },
  answerButton: {
    minHeight: 58,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#DDEBFF',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  answerButtonSelected: {
    backgroundColor: '#1F2A44',
    borderColor: '#1F2A44',
  },
  answerText: {
    color: '#1F2A44',
    fontSize: 16,
    fontWeight: '900',
  },
  answerTextSelected: {
    color: '#FFFFFF',
  },
  surveyFooter: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 16,
  },
  secondaryButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 16,
    backgroundColor: '#EAF3FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryButtonText: {
    color: '#315078',
    fontSize: 14,
    fontWeight: '900',
  },
  disabledButton: {
    opacity: 0.45,
  },
  tieNotice: {
    borderRadius: 18,
    backgroundColor: '#FFF7D6',
    borderWidth: 1,
    borderColor: '#FFE08A',
    padding: 16,
    marginBottom: 16,
  },
  tieNoticeTitle: {
    color: '#1F2A44',
    fontSize: 17,
    fontWeight: '900',
    marginBottom: 6,
  },
  tieNoticeText: {
    color: '#40566F',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '700',
  },
  resultHero: {
    borderRadius: 24,
    padding: 22,
    borderWidth: 1,
    borderColor: '#E3EDF8',
  },
  resultIcon: {
    fontSize: 58,
    marginBottom: 12,
  },
  resultKicker: {
    fontSize: 15,
    fontWeight: '900',
    marginBottom: 8,
  },
  resultTitle: {
    color: '#1F2A44',
    fontSize: 31,
    lineHeight: 39,
    fontWeight: '900',
  },
  resultSubtitle: {
    color: '#42526E',
    fontSize: 18,
    fontWeight: '900',
    marginTop: 8,
  },
  imageBox: {
    minHeight: 150,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    marginTop: 22,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
    borderWidth: 1,
    borderColor: '#E3EDF8',
  },
  imageIcon: {
    fontSize: 54,
    marginBottom: 10,
  },
  imageCaption: {
    color: '#52657A',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    textAlign: 'center',
  },
  scorePanel: {
    marginTop: 16,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E3EDF8',
    padding: 18,
    gap: 16,
  },
  scoreRow: {
    gap: 8,
  },
  scoreTopLine: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  scoreLabel: {
    color: '#1F2A44',
    fontSize: 15,
    fontWeight: '900',
  },
  scoreValue: {
    color: '#52657A',
    fontSize: 14,
    fontWeight: '900',
  },
  scoreTrack: {
    height: 10,
    borderRadius: 8,
    backgroundColor: '#EDF3FA',
    overflow: 'hidden',
  },
  scoreFill: {
    height: '100%',
    borderRadius: 8,
  },
  infoPanel: {
    marginTop: 16,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E3EDF8',
    padding: 20,
    marginBottom: 16,
  },
  sectionTitle: {
    color: '#1F2A44',
    fontSize: 18,
    fontWeight: '900',
    marginBottom: 8,
    marginTop: 4,
  },
  bodyText: {
    color: '#40566F',
    fontSize: 15,
    lineHeight: 23,
    fontWeight: '600',
    marginBottom: 16,
  },

  jobList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 2,
  },
  jobChip: {
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#E3EDF8',
  },
  jobChipText: {
    fontSize: 13,
    fontWeight: '900',
  },
  textButton: {
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 6,
  },
  textButtonLabel: {
    color: '#52657A',
    fontSize: 15,
    fontWeight: '900',
  },
  roadmapHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  backButton: {
    minHeight: 42,
    borderRadius: 14,
    backgroundColor: '#EAF3FF',
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backButtonText: {
    color: '#315078',
    fontSize: 14,
    fontWeight: '900',
  },
  roadmapType: {
    fontSize: 16,
    fontWeight: '900',
  },
  roadmapIntro: {
    borderRadius: 24,
    padding: 22,
    borderWidth: 1,
    borderColor: '#E3EDF8',
  },
  roadmapIcon: {
    fontSize: 52,
    marginBottom: 12,
  },
  roadmapTitle: {
    color: '#1F2A44',
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '900',
  },
  roadmapText: {
    color: '#40566F',
    fontSize: 15,
    lineHeight: 23,
    fontWeight: '700',
    marginTop: 10,
  },
  timeline: {
    marginTop: 18,
    marginBottom: 18,
    gap: 14,
  },
  timelineItem: {
    flexDirection: 'row',
    gap: 12,
  },
  timelineDot: {
    width: 42,
    height: 42,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timelineNumber: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '900',
  },
  timelineCard: {
    flex: 1,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E3EDF8',
    padding: 16,
  },
  timelineStep: {
    fontSize: 13,
    fontWeight: '900',
    marginBottom: 6,
  },
  timelineTitle: {
    color: '#1F2A44',
    fontSize: 18,
    lineHeight: 25,
    fontWeight: '900',
    marginBottom: 8,
  },
  timelinePlace: {
    color: '#52657A',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '900',
    marginBottom: 8,
  },
  timelineQuest: {
    color: '#40566F',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '600',
  },

  fairyRoadmap: {
    borderRadius: 24,
    backgroundColor: '#FFF8E8',
    borderWidth: 2,
    padding: 20,
    overflow: 'hidden',
  },
  fairySky: {
    minHeight: 76,
    borderRadius: 20,
    backgroundColor: '#DDF4FF',
    padding: 14,
    marginBottom: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  fairyCloud: {
    color: '#315078',
    fontSize: 14,
    fontWeight: '900',
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  fairyStar: {
    color: '#8A5A00',
    fontSize: 14,
    fontWeight: '900',
    backgroundColor: '#FFE9A8',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  fairyIcon: {
    fontSize: 58,
    textAlign: 'center',
    marginBottom: 10,
  },
  fairyTitle: {
    color: '#1F2A44',
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '900',
    textAlign: 'center',
  },
  fairyStory: {
    color: '#40566F',
    fontSize: 15,
    lineHeight: 23,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 10,
    marginBottom: 18,
  },
  fairyPath: {
    gap: 14,
  },
  fairyStep: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  fairyStepBadge: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fairyStepNumber: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '900',
  },
  fairyStepCard: {
    flex: 1,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#F1DFAF',
    padding: 15,
  },
  fairyStepTitle: {
    color: '#8A5A00',
    fontSize: 13,
    fontWeight: '900',
    marginBottom: 6,
  },
  fairyStepText: {
    color: '#1F2A44',
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '800',
  },

  puzzleGuideText: {
    color: '#40566F',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '900',
    textAlign: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#F1DFAF',
    paddingHorizontal: 12,
    paddingVertical: 9,
    marginBottom: 8,
  },
  puzzleBoard: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 2,
  },
  puzzlePiece: {
    width: '48%',
    minHeight: 82,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E3EDF8',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
  },
  puzzlePieceText: {
    color: '#8A9AAF',
    fontSize: 15,
    fontWeight: '900',
  },
  puzzlePieceTextActive: {
    color: '#FFFFFF',
    fontSize: 24,
  },
  completedGiftBox: {
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#F1DFAF',
    padding: 16,
    marginTop: 16,
  },
  completedGiftTitle: {
    color: '#1F2A44',
    fontSize: 18,
    fontWeight: '900',
    marginBottom: 8,
  },
  completedGiftText: {
    color: '#40566F',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '700',
    marginBottom: 12,
  },
  diaryGiftButton: {
    minHeight: 50,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1F2A44',
  },
  missionList: {
    marginTop: 18,
    gap: 12,
  },
  missionCard: {
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E3EDF8',
    overflow: 'hidden',
  },
  missionCardLocked: {
    opacity: 0.58,
  },
  missionButton: {
    minHeight: 84,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  missionBadge: {
    width: 48,
    height: 48,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  missionBadgeText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '900',
    textAlign: 'center',
  },
  missionButtonTextWrap: {
    flex: 1,
  },
  missionStep: {
    color: '#52657A',
    fontSize: 13,
    fontWeight: '900',
    marginBottom: 5,
  },
  missionTitle: {
    color: '#1F2A44',
    fontSize: 17,
    lineHeight: 24,
    fontWeight: '900',
  },
  missionDetail: {
    borderTopWidth: 1,
    borderTopColor: '#E3EDF8',
    padding: 16,
    backgroundColor: '#FBFDFF',
  },
  missionDetailLabel: {
    color: '#1F2A44',
    fontSize: 14,
    fontWeight: '900',
    marginBottom: 6,
  },
  missionDetailText: {
    color: '#40566F',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '700',
    marginBottom: 14,
  },
  recordPanel: {
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E3EDF8',
    padding: 14,
  },
  recordTitle: {
    color: '#1F2A44',
    fontSize: 16,
    fontWeight: '900',
    marginBottom: 10,
  },
  recordInput: {
    minHeight: 130,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#DDEBFF',
    backgroundColor: '#FFFFFF',
    padding: 12,
    color: '#1F2A44',
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '600',
  },
  recordActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 12,
  },
  recordSaveText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
  },
  savedRecordBox: {
    borderRadius: 14,
    backgroundColor: '#FFF8E8',
    borderWidth: 1,
    borderColor: '#F1DFAF',
    padding: 12,
    marginBottom: 12,
  },
  savedRecordLabel: {
    color: '#8A5A00',
    fontSize: 13,
    fontWeight: '900',
    marginBottom: 5,
  },
  savedRecordText: {
    color: '#40566F',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '700',
  },
  recordButton: {
    minHeight: 48,
    borderRadius: 16,
    backgroundColor: '#EAF3FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  recordButtonText: {
    color: '#315078',
    fontSize: 14,
    fontWeight: '900',
  },
  missionSuccessButton: {
    minHeight: 52,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },


  experienceSummaryPanel: {
    marginTop: 0,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E3EDF8',
    padding: 20,
    marginBottom: 16,
  },
  experienceSummaryText: {
    color: '#1F2A44',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '900',
  },
  experienceHero: {
    borderRadius: 24,
    backgroundColor: '#FFF7D6',
    borderWidth: 1,
    borderColor: '#FFE08A',
    padding: 22,
    marginBottom: 16,
  },
  experienceHeroIcon: {
    fontSize: 42,
    marginBottom: 10,
  },
  experienceHeroTitle: {
    color: '#1F2A44',
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '900',
  },
  experienceHeroText: {
    color: '#40566F',
    fontSize: 15,
    lineHeight: 23,
    fontWeight: '700',
    marginTop: 8,
  },
  experienceStatsRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 16,
  },
  experienceStatBox: {
    flex: 1,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#F1DFAF',
    padding: 14,
  },
  experienceStatValue: {
    color: '#1F2A44',
    fontSize: 24,
    fontWeight: '900',
  },
  experienceStatLabel: {
    color: '#52657A',
    fontSize: 13,
    fontWeight: '800',
    marginTop: 4,
  },
  experienceScorePanel: {
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E3EDF8',
    padding: 16,
    gap: 10,
    marginBottom: 16,
  },
  experienceScoreRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  experienceScoreLabel: {
    color: '#1F2A44',
    fontSize: 15,
    fontWeight: '900',
  },
  experienceScoreValue: {
    fontSize: 15,
    fontWeight: '900',
  },
  experienceMissionList: {
    gap: 10,
    marginBottom: 16,
  },
  experienceMissionButton: {
    minHeight: 82,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E3EDF8',
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  experienceMissionType: {
    borderRadius: 13,
    paddingHorizontal: 9,
    paddingVertical: 7,
  },
  experienceMissionTypeText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '900',
  },
  experienceMissionTextWrap: {
    flex: 1,
  },
  experienceMissionTitle: {
    color: '#1F2A44',
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '900',
  },
  experienceMissionMeta: {
    color: '#52657A',
    fontSize: 13,
    fontWeight: '800',
    marginTop: 4,
  },
  experienceMissionStatus: {
    color: '#8A9AAF',
    fontSize: 13,
    fontWeight: '900',
  },
  experienceCertPanel: {
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E3EDF8',
    padding: 20,
  },
  experienceCertLabel: {
    color: '#1F2A44',
    fontSize: 14,
    fontWeight: '900',
    marginBottom: 6,
  },
  experienceCertText: {
    color: '#40566F',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '700',
    marginBottom: 14,
  },
  gpsButton: {
    minHeight: 50,
    borderRadius: 16,
    backgroundColor: '#EAF3FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  gpsButtonText: {
    color: '#315078',
    fontSize: 14,
    fontWeight: '900',
  },
  experienceStatusText: {
    color: '#40566F',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '800',
    marginBottom: 12,
  },


  portfolioHomeButton: {
    minHeight: 86,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#DDEBFF',
    marginTop: 12,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  portfolioHero: {
    borderRadius: 24,
    backgroundColor: '#FFF7D6',
    borderWidth: 1,
    borderColor: '#FFE08A',
    padding: 22,
    marginBottom: 16,
  },
  portfolioIcon: {
    fontSize: 44,
    marginBottom: 10,
  },
  portfolioTitle: {
    color: '#1F2A44',
    fontSize: 30,
    lineHeight: 38,
    fontWeight: '900',
  },
  portfolioSubtitle: {
    color: '#40566F',
    fontSize: 15,
    lineHeight: 23,
    fontWeight: '700',
    marginTop: 8,
    marginBottom: 16,
  },
  portfolioSection: {
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E3EDF8',
    padding: 18,
    marginBottom: 14,
  },
  portfolioSectionTitle: {
    color: '#1F2A44',
    fontSize: 19,
    fontWeight: '900',
    marginBottom: 12,
  },
  portfolioProfileRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#EDF3FA',
    paddingVertical: 10,
  },
  portfolioProfileLabel: {
    color: '#52657A',
    fontSize: 14,
    fontWeight: '900',
  },
  portfolioProfileValue: {
    flex: 1,
    color: '#1F2A44',
    fontSize: 14,
    fontWeight: '900',
    textAlign: 'right',
  },
  portfolioScoreRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  portfolioScoreLabel: {
    width: 58,
    color: '#1F2A44',
    fontSize: 14,
    fontWeight: '900',
  },
  portfolioScoreTrack: {
    flex: 1,
    height: 12,
    borderRadius: 8,
    backgroundColor: '#EDF3FA',
    overflow: 'hidden',
  },
  portfolioScoreFill: {
    height: '100%',
    borderRadius: 8,
  },
  portfolioScoreValue: {
    width: 36,
    color: '#52657A',
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'right',
  },
  portfolioListItem: {
    borderRadius: 16,
    backgroundColor: '#F7FBFF',
    borderWidth: 1,
    borderColor: '#DDEBFF',
    padding: 14,
    marginBottom: 10,
  },
  portfolioListTitle: {
    color: '#1F2A44',
    fontSize: 15,
    lineHeight: 21,
    fontWeight: '900',
    marginBottom: 5,
  },
  portfolioListText: {
    color: '#52657A',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '700',
    marginTop: 3,
  },
  portfolioEmptyText: {
    color: '#8A9AAF',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '800',
  },
  portfolioSummaryText: {
    color: '#40566F',
    fontSize: 15,
    lineHeight: 24,
    fontWeight: '800',
  },
  portfolioPrintButton: {
    minHeight: 56,
    borderRadius: 18,
    backgroundColor: '#1F2A44',
    alignItems: 'center',
    justifyContent: 'center',
  },
  parentHomeButton: {
    minHeight: 86,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#DDEBFF',
    marginTop: 12,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  parentHero: {
    borderRadius: 24,
    backgroundColor: '#EAF8EF',
    borderWidth: 1,
    borderColor: '#CFEFDA',
    padding: 22,
    marginBottom: 16,
  },
  parentHeroIcon: {
    fontSize: 44,
    marginBottom: 10,
  },
  parentHeroTitle: {
    color: '#1F2A44',
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '900',
  },
  parentHeroText: {
    color: '#40566F',
    fontSize: 15,
    lineHeight: 23,
    fontWeight: '700',
    marginTop: 8,
  },
  parentPanel: {
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E3EDF8',
    padding: 18,
    marginBottom: 14,
  },
  growthGraph: {
    gap: 16,
  },
  growthSnapshotRow: {
    gap: 8,
  },
  growthSnapshotLabel: {
    color: '#1F2A44',
    fontSize: 15,
    fontWeight: '900',
  },
  growthBars: {
    gap: 7,
  },
  growthBarLine: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  growthBarLabel: {
    width: 52,
    color: '#52657A',
    fontSize: 12,
    fontWeight: '900',
  },
  growthBarTrack: {
    flex: 1,
    height: 12,
    borderRadius: 8,
    backgroundColor: '#EDF3FA',
    overflow: 'hidden',
  },
  growthBarFill: {
    height: '100%',
    borderRadius: 8,
  },
  growthBarValue: {
    width: 34,
    color: '#1F2A44',
    fontSize: 12,
    fontWeight: '900',
    textAlign: 'right',
  },
  parentReportText: {
    color: '#40566F',
    fontSize: 15,
    lineHeight: 23,
    fontWeight: '700',
  },
  parentInsightGrid: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 14,
  },
  parentInsightCard: {
    flex: 1,
    borderRadius: 16,
    backgroundColor: '#F7FBFF',
    borderWidth: 1,
    borderColor: '#DDEBFF',
    padding: 12,
  },
  parentInsightValue: {
    fontSize: 22,
    fontWeight: '900',
  },
  parentInsightLabel: {
    color: '#52657A',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 4,
  },
  parentMissionRow: {
    borderRadius: 16,
    backgroundColor: '#F7FBFF',
    borderWidth: 1,
    borderColor: '#DDEBFF',
    padding: 14,
    marginBottom: 10,
  },
  parentMissionTitle: {
    color: '#1F2A44',
    fontSize: 15,
    fontWeight: '900',
    marginBottom: 5,
  },
  parentMissionMeta: {
    color: '#52657A',
    fontSize: 13,
    fontWeight: '800',
  },
  parentActivityRow: {
    flexDirection: 'row',
    gap: 10,
    borderRadius: 16,
    backgroundColor: '#F7FBFF',
    borderWidth: 1,
    borderColor: '#DDEBFF',
    padding: 14,
    marginBottom: 10,
  },
  parentActivityDistrict: {
    color: '#2F80ED',
    fontSize: 13,
    fontWeight: '900',
  },
  parentActivityTextWrap: {
    flex: 1,
  },
  parentActivityTitle: {
    color: '#1F2A44',
    fontSize: 15,
    fontWeight: '900',
    marginBottom: 5,
  },
  parentActivityText: {
    color: '#52657A',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '700',
  },
  parentPrintButton: {
    minHeight: 54,
    borderRadius: 17,
    backgroundColor: '#1F2A44',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 14,
  },
  activityIntroPanel: {
    borderRadius: 24,
    backgroundColor: '#EAF3FF',
    borderWidth: 1,
    borderColor: '#DDEBFF',
    padding: 22,
    marginBottom: 16,
  },
  activityIntroIcon: {
    fontSize: 46,
    marginBottom: 10,
  },
  activityIntroTitle: {
    color: '#1F2A44',
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '900',
  },
  activityIntroText: {
    color: '#40566F',
    fontSize: 15,
    lineHeight: 23,
    fontWeight: '700',
    marginTop: 8,
    marginBottom: 16,
  },
  activityMapToggleButton: {
    minHeight: 54,
    borderRadius: 17,
    backgroundColor: '#2F80ED',
    alignItems: 'center',
    justifyContent: 'center',
  },
  kakaoMapShell: {
    minHeight: 360,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#DDEBFF',
    overflow: 'hidden',
    marginBottom: 16,
  },
  kakaoMapCanvas: {
    minHeight: 360,
    width: '100%',
  },
  kakaoMapNotice: {
    position: 'absolute',
    left: 16,
    right: 16,
    top: 130,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#DDEBFF',
    padding: 14,
  },
  kakaoMapNoticeText: {
    color: '#40566F',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '800',
    textAlign: 'center',
  },
  activityList: {
    gap: 12,
  },
  activityCard: {
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E3EDF8',
    padding: 16,
  },
  activityCardTopLine: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 10,
  },
  activityDistrict: {
    color: '#2F80ED',
    fontSize: 13,
    fontWeight: '900',
    backgroundColor: '#EAF3FF',
    borderRadius: 13,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  activityPlace: {
    flex: 1,
    color: '#52657A',
    fontSize: 13,
    fontWeight: '800',
    textAlign: 'right',
  },
  activityTitle: {
    color: '#1F2A44',
    fontSize: 19,
    lineHeight: 26,
    fontWeight: '900',
    marginBottom: 8,
  },
  activityInfo: {
    color: '#40566F',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '700',
    marginBottom: 10,
  },
  activityAddress: {
    color: '#8A9AAF',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '800',
  },
  diaryPanel: {
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E3EDF8',
    padding: 20,
  },
  diaryTitle: {
    color: '#1F2A44',
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '900',
  },
  diarySubtitle: {
    color: '#40566F',
    fontSize: 15,
    lineHeight: 23,
    fontWeight: '700',
    marginTop: 8,
    marginBottom: 18,
  },
  diaryLabel: {
    color: '#1F2A44',
    fontSize: 14,
    fontWeight: '900',
    marginBottom: 7,
  },
  diaryInput: {
    minHeight: 50,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#DDEBFF',
    backgroundColor: '#FBFDFF',
    paddingHorizontal: 14,
    paddingVertical: 10,
    color: '#1F2A44',
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 14,
  },
  diaryContentInput: {
    minHeight: 150,
    lineHeight: 22,
  },
  diarySaveButton: {
    minHeight: 54,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },

  diaryTopLine: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  diaryTitleWrap: {
    flex: 1,
  },
  diaryCountBadge: {
    minWidth: 46,
    borderRadius: 14,
    backgroundColor: '#F7FBFF',
    borderWidth: 1,
    borderColor: '#DDEBFF',
    paddingHorizontal: 10,
    paddingVertical: 7,
    textAlign: 'center',
    fontSize: 13,
    fontWeight: '900',
  },
  diaryAddButton: {
    minHeight: 52,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  diaryEntryList: {
    gap: 10,
  },
  diaryEmptyBox: {
    borderRadius: 18,
    backgroundColor: '#F7FBFF',
    borderWidth: 1,
    borderColor: '#DDEBFF',
    padding: 16,
  },
  diaryEmptyTitle: {
    color: '#1F2A44',
    fontSize: 16,
    fontWeight: '900',
    marginBottom: 6,
  },
  diaryEmptyText: {
    color: '#52657A',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '700',
  },
  diaryEntryItem: {
    minHeight: 92,
    borderRadius: 18,
    backgroundColor: '#FBFDFF',
    borderWidth: 1,
    borderColor: '#DDEBFF',
    padding: 14,
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
  },
  diaryEntryDateBox: {
    minWidth: 96,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E3EDF8',
    paddingHorizontal: 10,
    paddingVertical: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  diaryEntryDate: {
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'center',
  },
  diaryEntryTextWrap: {
    flex: 1,
  },
  diaryEntryGoal: {
    color: '#1F2A44',
    fontSize: 15,
    lineHeight: 21,
    fontWeight: '900',
    marginBottom: 5,
  },
  diaryEntryPreview: {
    color: '#52657A',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '700',
  },
  diaryFormActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 2,
  },
  diaryDetailBox: {
    borderRadius: 18,
    backgroundColor: '#FBFDFF',
    borderWidth: 1,
    borderColor: '#DDEBFF',
    padding: 16,
    marginBottom: 16,
  },
  diaryDetailLabel: {
    color: '#1F2A44',
    fontSize: 14,
    fontWeight: '900',
    marginBottom: 6,
  },
  diaryDetailText: {
    color: '#40566F',
    fontSize: 15,
    lineHeight: 23,
    fontWeight: '700',
    marginBottom: 14,
  },
});
