import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F7FBFF',
  },
  container: {
    padding: 20,
    paddingBottom: 36,
  },
  hero: {
    minHeight: 520,
    borderRadius: 24,
    backgroundColor: '#FFF7D6',
    padding: 22,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#FFE08A',
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  brand: {
    color: '#1F2A44',
    fontSize: 24,
    fontWeight: '900',
  },
  badge: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderWidth: 1,
    borderColor: '#DDEBFF',
  },
  badgeText: {
    color: '#315078',
    fontSize: 12,
    fontWeight: '800',
  },
  heroContent: {
    flex: 1,
    justifyContent: 'center',
    paddingVertical: 36,
  },
  heroImage: {
    width: 118,
    height: 118,
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 22,
    borderWidth: 1,
    borderColor: '#FFE08A',
  },
  heroIcon: {
    fontSize: 58,
  },
  eyebrow: {
    color: '#2F80ED',
    fontSize: 15,
    fontWeight: '900',
    marginBottom: 10,
  },
  title: {
    color: '#1F2A44',
    fontSize: 34,
    lineHeight: 42,
    fontWeight: '900',
    maxWidth: 350,
  },
  subtitle: {
    color: '#42526E',
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
    marginTop: 14,
    maxWidth: 350,
  },
  primaryButton: {
    minHeight: 56,
    borderRadius: 18,
    backgroundColor: '#2F80ED',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    shadowColor: '#1D5FBF',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.16,
    shadowRadius: 14,
    elevation: 5,
    overflow: 'hidden',
  },
  pressed: {
    opacity: 0.72,
    transform: [{ scale: 0.98 }],
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '900',
    textAlign: 'center',
  },
  typeGrid: {
    marginTop: 18,
    gap: 12,
  },
  typeCard: {
    minHeight: 116,
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: '#E3EDF8',
  },
  typeIcon: {
    fontSize: 34,
    marginBottom: 8,
  },
  typeTitle: {
    color: '#1F2A44',
    fontSize: 19,
    fontWeight: '900',
  },
  typeDescription: {
    color: '#52657A',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '700',
    marginTop: 4,
  },
  surveyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  progressText: {
    color: '#52657A',
    fontSize: 14,
    fontWeight: '800',
  },
  progressTrack: {
    height: 12,
    borderRadius: 8,
    backgroundColor: '#E3EDF8',
    overflow: 'hidden',
    marginBottom: 18,
  },
  progressFill: {
    height: '100%',
    borderRadius: 8,
    backgroundColor: '#2F80ED',
  },
  questionCard: {
    minHeight: 260,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E3EDF8',
    padding: 22,
    justifyContent: 'center',
  },
  questionTypeBadge: {
    alignSelf: 'flex-start',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 7,
    marginBottom: 22,
  },
  questionTypeText: {
    fontSize: 13,
    fontWeight: '900',
  },
  questionNumber: {
    color: '#8A9AAF',
    fontSize: 18,
    fontWeight: '900',
    marginBottom: 10,
  },
  questionText: {
    color: '#1F2A44',
    fontSize: 24,
    lineHeight: 34,
    fontWeight: '900',
  },
  answerList: {
    marginTop: 16,
    gap: 10,
  },
  answerButton: {
    minHeight: 58,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#DDEBFF',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  answerButtonSelected: {
    backgroundColor: '#1F2A44',
    borderColor: '#1F2A44',
  },
  answerText: {
    color: '#1F2A44',
    fontSize: 16,
    fontWeight: '900',
  },
  answerTextSelected: {
    color: '#FFFFFF',
  },
  surveyFooter: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 16,
  },
  secondaryButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 16,
    backgroundColor: '#EAF3FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryButtonText: {
    color: '#315078',
    fontSize: 14,
    fontWeight: '900',
  },
  disabledButton: {
    opacity: 0.45,
  },
  tieNotice: {
    borderRadius: 18,
    backgroundColor: '#FFF7D6',
    borderWidth: 1,
    borderColor: '#FFE08A',
    padding: 16,
    marginBottom: 16,
  },
  tieNoticeTitle: {
    color: '#1F2A44',
    fontSize: 17,
    fontWeight: '900',
    marginBottom: 6,
  },
  tieNoticeText: {
    color: '#40566F',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '700',
  },
  resultHero: {
    borderRadius: 24,
    padding: 22,
    borderWidth: 1,
    borderColor: '#E3EDF8',
  },
  resultIcon: {
    fontSize: 58,
    marginBottom: 12,
  },
  resultKicker: {
    fontSize: 15,
    fontWeight: '900',
    marginBottom: 8,
  },
  resultTitle: {
    color: '#1F2A44',
    fontSize: 31,
    lineHeight: 39,
    fontWeight: '900',
  },
  resultSubtitle: {
    color: '#42526E',
    fontSize: 18,
    fontWeight: '900',
    marginTop: 8,
  },
  imageBox: {
    minHeight: 150,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    marginTop: 22,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
    borderWidth: 1,
    borderColor: '#E3EDF8',
  },
  imageIcon: {
    fontSize: 54,
    marginBottom: 10,
  },
  imageCaption: {
    color: '#52657A',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    textAlign: 'center',
  },
  scorePanel: {
    marginTop: 16,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E3EDF8',
    padding: 18,
    gap: 16,
  },
  scoreRow: {
    gap: 8,
  },
  scoreTopLine: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  scoreLabel: {
    color: '#1F2A44',
    fontSize: 15,
    fontWeight: '900',
  },
  scoreValue: {
    color: '#52657A',
    fontSize: 14,
    fontWeight: '900',
  },
  scoreTrack: {
    height: 10,
    borderRadius: 8,
    backgroundColor: '#EDF3FA',
    overflow: 'hidden',
  },
  scoreFill: {
    height: '100%',
    borderRadius: 8,
  },
  infoPanel: {
    marginTop: 16,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E3EDF8',
    padding: 20,
    marginBottom: 16,
  },
  sectionTitle: {
    color: '#1F2A44',
    fontSize: 18,
    fontWeight: '900',
    marginBottom: 8,
    marginTop: 4,
  },
  bodyText: {
    color: '#40566F',
    fontSize: 15,
    lineHeight: 23,
    fontWeight: '600',
    marginBottom: 16,
  },
  textButton: {
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 6,
  },
  textButtonLabel: {
    color: '#52657A',
    fontSize: 15,
    fontWeight: '900',
  },
  roadmapHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  backButton: {
    minHeight: 42,
    borderRadius: 14,
    backgroundColor: '#EAF3FF',
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backButtonText: {
    color: '#315078',
    fontSize: 14,
    fontWeight: '900',
  },
  roadmapType: {
    fontSize: 16,
    fontWeight: '900',
  },
  roadmapIntro: {
    borderRadius: 24,
    padding: 22,
    borderWidth: 1,
    borderColor: '#E3EDF8',
  },
  roadmapIcon: {
    fontSize: 52,
    marginBottom: 12,
  },
  roadmapTitle: {
    color: '#1F2A44',
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '900',
  },
  roadmapText: {
    color: '#40566F',
    fontSize: 15,
    lineHeight: 23,
    fontWeight: '700',
    marginTop: 10,
  },
  timeline: {
    marginTop: 18,
    marginBottom: 18,
    gap: 14,
  },
  timelineItem: {
    flexDirection: 'row',
    gap: 12,
  },
  timelineDot: {
    width: 42,
    height: 42,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timelineNumber: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '900',
  },
  timelineCard: {
    flex: 1,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E3EDF8',
    padding: 16,
  },
  timelineStep: {
    fontSize: 13,
    fontWeight: '900',
    marginBottom: 6,
  },
  timelineTitle: {
    color: '#1F2A44',
    fontSize: 18,
    lineHeight: 25,
    fontWeight: '900',
    marginBottom: 8,
  },
  timelinePlace: {
    color: '#52657A',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '900',
    marginBottom: 8,
  },
  timelineQuest: {
    color: '#40566F',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '600',
  },
});
